CREATE TABLE T_PASSENGER(
	PASSENGER_ID INTEGER NOT NULL AUTO_INCREMENT,
    PASSENGERS_NAME VARCHAR(25),
    AGE INTEGER(2),
    MOBILE_NO VARCHAR(12),
    AADHAAR_NO VARCHAR(12),
    STATE VARCHAR(20),
    TRAIN_NO varchar(20) not null,
    TRAIN_NAME VARCHAR(20) not null,
	SRC VARCHAR(20) not null,
    DESTINATION VARCHAR(20) not null,
	DEPARTURE_TIME TIME not NULL,
    AVAIL_DATE DATE not null,
    TICKET_PRICE VARCHAR(10),
    TICKET_NO INT NOT NULL,
	TICKET_CATEGORY VARCHAR(25),
	CONSTRAINT PK_PASSENGER_ID PRIMARY KEY(PASSENGER_ID),
    CONSTRAINT FKTRAIN_NO FOREIGN KEY(TRAIN_NO) REFERENCES T_TRAIN(TRAIN_NO)
)AUTO_INCREMENT = 4000;
