CREATE TABLE T_TRAIN(
	TRAIN_NO varchar(20) not null,
    TRAIN_NAME VARCHAR(20) not null,
    SRC VARCHAR(20) not null,
    DESTINATION VARCHAR(20) not null,
    DEPARTURE_TIME TIME not NULL,
    AVAIL_DATE DATE not null,
    AVAIL_SEATS VARCHAR(5),
    CONSTRAINT PK_TRAIN_NO PRIMARY KEY(TRAIN_NO)
);

